# Generated by Django 4.2 on 2023-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_code_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeconfirmation',
            name='code_token',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
